package main

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *DataV2) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "message":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
			if z.Message == nil {
				z.Message = make(map[string]interface{}, zb0002)
			} else if len(z.Message) > 0 {
				for key := range z.Message {
					delete(z.Message, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 interface{}
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Message")
					return
				}
				za0002, err = dc.ReadIntf()
				if err != nil {
					err = msgp.WrapError(err, "Message", za0001)
					return
				}
				z.Message[za0001] = za0002
			}
		case "tag":
			z.Tag, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Tag")
				return
			}
		case "id":
			z.Id, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "exts":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Exts")
				return
			}
			if cap(z.Exts) >= int(zb0003) {
				z.Exts = (z.Exts)[:zb0003]
			} else {
				z.Exts = make([]int64, zb0003)
			}
			for za0003 := range z.Exts {
				z.Exts[za0003], err = dc.ReadInt64()
				if err != nil {
					err = msgp.WrapError(err, "Exts", za0003)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *DataV2) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "message"
	err = en.Append(0x84, 0xa7, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Message)))
	if err != nil {
		err = msgp.WrapError(err, "Message")
		return
	}
	for za0001, za0002 := range z.Message {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Message")
			return
		}
		err = en.WriteIntf(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Message", za0001)
			return
		}
	}
	// write "tag"
	err = en.Append(0xa3, 0x74, 0x61, 0x67)
	if err != nil {
		return
	}
	err = en.WriteString(z.Tag)
	if err != nil {
		err = msgp.WrapError(err, "Tag")
		return
	}
	// write "id"
	err = en.Append(0xa2, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Id)
	if err != nil {
		err = msgp.WrapError(err, "Id")
		return
	}
	// write "exts"
	err = en.Append(0xa4, 0x65, 0x78, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Exts)))
	if err != nil {
		err = msgp.WrapError(err, "Exts")
		return
	}
	for za0003 := range z.Exts {
		err = en.WriteInt64(z.Exts[za0003])
		if err != nil {
			err = msgp.WrapError(err, "Exts", za0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *DataV2) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "message"
	o = append(o, 0x84, 0xa7, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65)
	o = msgp.AppendMapHeader(o, uint32(len(z.Message)))
	for za0001, za0002 := range z.Message {
		o = msgp.AppendString(o, za0001)
		o, err = msgp.AppendIntf(o, za0002)
		if err != nil {
			err = msgp.WrapError(err, "Message", za0001)
			return
		}
	}
	// string "tag"
	o = append(o, 0xa3, 0x74, 0x61, 0x67)
	o = msgp.AppendString(o, z.Tag)
	// string "id"
	o = append(o, 0xa2, 0x69, 0x64)
	o = msgp.AppendInt64(o, z.Id)
	// string "exts"
	o = append(o, 0xa4, 0x65, 0x78, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Exts)))
	for za0003 := range z.Exts {
		o = msgp.AppendInt64(o, z.Exts[za0003])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DataV2) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "message":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
			if z.Message == nil {
				z.Message = make(map[string]interface{}, zb0002)
			} else if len(z.Message) > 0 {
				for key := range z.Message {
					delete(z.Message, key)
				}
			}
			for zb0002 > 0 {
				var za0001 string
				var za0002 interface{}
				zb0002--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Message")
					return
				}
				za0002, bts, err = msgp.ReadIntfBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Message", za0001)
					return
				}
				z.Message[za0001] = za0002
			}
		case "tag":
			z.Tag, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tag")
				return
			}
		case "id":
			z.Id, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Id")
				return
			}
		case "exts":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Exts")
				return
			}
			if cap(z.Exts) >= int(zb0003) {
				z.Exts = (z.Exts)[:zb0003]
			} else {
				z.Exts = make([]int64, zb0003)
			}
			for za0003 := range z.Exts {
				z.Exts[za0003], bts, err = msgp.ReadInt64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Exts", za0003)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *DataV2) Msgsize() (s int) {
	s = 1 + 8 + msgp.MapHeaderSize
	if z.Message != nil {
		for za0001, za0002 := range z.Message {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.GuessSize(za0002)
		}
	}
	s += 4 + msgp.StringPrefixSize + len(z.Tag) + 3 + msgp.Int64Size + 5 + msgp.ArrayHeaderSize + (len(z.Exts) * (msgp.Int64Size))
	return
}
