version: '3.1'

services:
  # configurations:
  #   - https://github.com/31z4/zookeeper-docker#configuration
  zoo1:
    image: zookeeper:3.4
    networks:
      - zk
    restart: always
    hostname: zoo1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - "./data/zoo1:/data"
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper:3.4
    networks:
      - zk
    restart: always
    hostname: zoo2
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - "./data/zoo2:/data"
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper:3.4
    networks:
      - zk
    restart: always
    hostname: zoo3
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - "./data/zoo3:/data"
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888


networks:
  zk:
