version: "2"
services:

  v2ray:
    image: v2ray/official:latest
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - ./conf/config.json:/etc/v2ray/config.json
    command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json
