// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dockerlog.proto

package dockerlog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Msg                  map[string]string `protobuf:"bytes,2,rep,name=msg" json:"msg,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tag                  string            `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
	Offset               int64             `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_dockerlog_00828a3836f3ff57, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsg() map[string]string {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Message) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Message) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "dockerlog.Message")
	proto.RegisterMapType((map[string]string)(nil), "dockerlog.Message.MsgEntry")
}

func init() { proto.RegisterFile("dockerlog.proto", fileDescriptor_dockerlog_00828a3836f3ff57) }

var fileDescriptor_dockerlog_00828a3836f3ff57 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xc9, 0x4f, 0xce,
	0x4e, 0x2d, 0xca, 0xc9, 0x4f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0xcd, 0x62, 0xe4, 0x62, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0xd2, 0xe5, 0x62, 0xce,
	0x2d, 0x4e, 0x97, 0x60, 0x52, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd6, 0x43, 0xe8, 0x82, 0x2a, 0xd0,
	0xf3, 0x2d, 0x4e, 0x77, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x02, 0xa9, 0x13, 0x12, 0xe0, 0x62, 0x2e,
	0x49, 0x4c, 0x97, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0xc4, 0xb8, 0xd8, 0xf2,
	0xd3, 0xd2, 0x8a, 0x53, 0x4b, 0x24, 0x58, 0x14, 0x18, 0x35, 0x98, 0x83, 0xa0, 0x3c, 0x29, 0x33,
	0x2e, 0x0e, 0x98, 0x56, 0x90, 0xae, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x88, 0xae, 0xec, 0xd4, 0x4a,
	0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0xb0, 0x18, 0x84, 0x63, 0xc5,
	0x64, 0xc1, 0x98, 0xc4, 0x06, 0x76, 0xae, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x64, 0x16,
	0xc5, 0xc1, 0x00, 0x00, 0x00,
}
