version: '3.1'

services:
  backend:
    image: debian:buster
    environment:
      VERSION: 1.0.1
    # entrypoint: sleep 1000000
    command: sleep 1000000
    # entrypoint: "exit 1"
    volumes:
      - /usr/local/bin/docker:/bin/docker
      - ./docker-compose.yml:/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
